# Generated by Django 4.2.11 on 2024-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_results_visitdetails_tests_patientresults_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientResults',
        ),
    ]
